function(configure_debian_package)
  if(NOT UNIX)
    message(FATAL_ERROR "Packaging debian package is only supported on linux.")
  endif()
  if(NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    message(WARNING "Debian packages only support Release versions, current type：${CMAKE_BUILD_TYPE}")
  endif()
  set(CPACK_GENERATOR "DEB")
  set(CPACK_SOURCE_GENERATOR "DEB")
  set(CPACK_DEBIAN_PACKAGE_NAME "ads")
  set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
  set(CPACK_PACKAGE_CONTACT "liufang_robot@outlook.com")
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "liufang <${CPACK_PACKAGE_CONTACT}>")
  set(CPACK_PACKAGE_FILE_NAME "ads-${ADSLIB_VERSION}-linux-${CMAKE_BUILD_TYPE}")
  include(CPack)
endfunction()

function(configure_windows_package)
  if(NOT WIN32)
    message(
      FATAL_ERROR "Packaging windows package is only supported on windows.")
  endif()
  set(CPACK_GENERATOR "NSIS64")
  set(CPACK_PACKAGE_NAME "ads")
  set(CPACK_SOURCE_GENERATOR "NSIS")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "ads")
  set(CPACK_NSIS_PACKAGE_NAME "ads")
  set(CPACK_NSIS_DISPLAY_NAME "ads")
  set(CPACK_NSIS_CONTACT "liufang_robot@outlook.com")
  set(CPACK_NSIS_MODIFY_PATH ON)
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
  if(NOT DEFINED USE_TWINCAT_ROUTER)
    set(USE_TWINCAT_ROUTER OFF)
  endif()
  if(USE_TWINCAT_ROUTER)
    set(PACKAGE_SUFFIX "-twincat")
  else()
    set(PACKAGE_SUFFIX "")
  endif()
  # CMAKE_BUILD_TYPE 在 workflow中定义
  set(CPACK_PACKAGE_FILE_NAME "ads${PACKAGE_SUFFIX}-${ADSLIB_VERSION}-win64-${CMAKE_BUILD_TYPE}")

  include(CPack)
endfunction()
