macro(configure_debian_packaging)
  set(CPACK_GENERATOR "DEB")
  set(CPACK_SOURCE_GENERATOR "DEB")
  set(CPACK_DEBIAN_PACKAGE_NAME ${PROJECT_NAME})
  set(CPACK_PACKAGE_CONTACT "liufang_robot@outlook.com")
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "liufang <${CPACK_PACKAGE_CONTACT}>")
endmacro()

macro(configure_windows_packaging)
  set(CPACK_GENERATOR "NSIS64")
  set(CPACK_SOURCE_GENERATOR "NSIS")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME})
  set(CPACK_NSIS_PACKAGE_NAME ${PROJECT_NAME})
  set(CPACK_NSIS_DISPLAY_NAME ${PROJECT_NAME})
  set(CPACK_NSIS_CONTACT "liufang_robot@outlook.com")
  set(CPACK_NSIS_MODIFY_PATH ON)
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
endmacro()

function(configure_packaging)
  set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
  set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
  if(UNIX)
    configure_debian_packaging()
  elseif(WIN32)
    configure_windows_packaging()
  endif()
  include(CPack)
endfunction()
