function(configure_debian_package)
  if(NOT UNIX)
    message(FATAL_ERROR "Packaging debian package is only supported on linux.")
  endif()
  set(CPACK_GENERATOR "DEB")
  set(CPACK_SOURCE_GENERATOR "DEB")
  set(CPACK_DEBIAN_PACKAGE_NAME "ads")
  set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
  set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
  set(CPACK_PACKAGE_CONTACT "liufang_robot@outlook.com")
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "liufang <${CPACK_PACKAGE_CONTACT}>")
  include(CPack)
endfunction()

function(configure_windows_package)
  if(NOT WIN32)
    message(
      FATAL_ERROR "Packaging windows package is only supported on windows.")
  endif()
  set(CPACK_GENERATOR "NSIS64")
  set(CPACK_PACKAGE_NAME "ads")
  set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
  set(CPACK_SOURCE_GENERATOR "NSIS")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "ads")
  set(CPACK_NSIS_PACKAGE_NAME "ads")
  set(CPACK_NSIS_DISPLAY_NAME "ads")
  set(CPACK_NSIS_CONTACT "liufang_robot@outlook.com")
  set(CPACK_NSIS_MODIFY_PATH ON)
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
  include(CPack)
endfunction()
