name: Build and Package ADS on Windows

on:
 push:
   paths:
     - .github/workflows/build-package-windows.yml
 pull_request:
   paths:
     - .github/workflows/build-package-windows.yml


permissions:
  contents: write
  pull-requests: write

jobs:
  build-package-windows:
#    runs-on: [self-hosted, windows, x64, twincat]
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Release, Debug]
    steps:
      - uses: actions/checkout@v4

      - name: Build and Package ADS
        shell: pwsh
        run: |
          $env:TwinCAT_ROOT="C:\TwinCAT"
          echo "TwinCAT_ROOT is set to $env:TwinCAT_ROOT"
          
          if (-Not (Test-Path build)) {
            New-Item -ItemType Directory -Force -Path build
          }
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_TWINCAT_ROUTER=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build . --config ${{ matrix.build_type }}
          cpack -G NSIS64 -C ${{ matrix.build_type }}
          

      - name: Extract Version from Release
        shell: pwsh
        run: |
            cd build
            $exeFile = Get-ChildItem -Filter "ads-*.exe" | Sort-Object Name -Descending | Select-Object -First 1
            if ($exeFile.Name -match "ads-([\d\.]+)-") {
            echo "VERSION=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            echo "Failed to extract version"
            exit 1
          }

      - name: Rename Executables add build_type
        shell: pwsh
        run: |
          cd build
          $exeFile = Get-ChildItem -Filter "ads-*.exe" | Sort-Object Name -Descending | Select-Object -First 1
          if ($exeFile) {
            $newName = $exeFile.Name -replace "(?<=ads-[\d\w\.-]+)(\.exe)$", "-${{ matrix.build_type }}.exe"
            Rename-Item -Path $exeFile.FullName -NewName $newName
            echo "Renamed $($exeFile.Name) to $newName"
          } else {
            echo "No executable found!"
            exit 1
          }

      - name: Release the Package
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"
          files: |
            build/*.exe

