name: Build and Package ADS on Windows

on:
  push:
    paths:
      - .github/workflows/build-package-windows.yml
  pull_request:
    paths:
      - .github/workflows/build-package-windows.yml

permissions:
  contents: write

jobs:
  build-package-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Release, Debug]
        twincat: [ON,OFF]
    steps:
      - uses: actions/checkout@v4

      - name: Configure and Build ADS
        shell: pwsh
        run: |
          mkdir build 
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_TWINCAT_ROUTER=${{ matrix.twincat }}
          cmake --build . --config ${{ matrix.build_type }}
    

      - name: Package ADS with CPack
        shell: pwsh
        run: |
          cd build
          cpack -G NSIS64 -C ${{ matrix.build_type }}

      - name: Set Tag Name
        shell: pwsh
        run: |
          if ("${{ matrix.twincat }}" -eq "ON") {
            echo "TAG_NAME=${{ matrix.build_type }}-use-twincat" >> $env:GITHUB_ENV
          } else {
            echo "TAG_NAME=${{ matrix.build_type }}-without-twincat" >> $env:GITHUB_ENV
          }

      - name: Release the Package
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ads*-${{ matrix.build_type }}.exe
          tag: "${{ env.TAG_NAME }}_Windows"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true

