name: Build and Package ADS on Windows

#on:
#  push:
#    paths:
#      - .github/workflows/build-package-windows.yml
#  pull_request:
#    paths:
#      - .github/workflows/build-package-windows.yml

on: push

permissions:
  contents: write
  pull-requests: write

jobs:
  build-package-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Release, Debug]
        twincat: [ON, OFF]
    steps:
      - uses: actions/checkout@v4

      - name: Configure and Build ADS
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_TWINCAT_ROUTER=${{ matrix.twincat }}
          cmake --build . --config ${{ matrix.build_type }}

      - name: Package ADS with CPack
        shell: pwsh
        run: |
          cd build
          cpack -G NSIS64 -C ${{ matrix.build_type }}

      - name: Extract Version from Release
        shell: pwsh
        run: |
          cd build
          $exeFile = Get-ChildItem -Filter "ads-*-win64-*.exe" | Select-Object -First 1
          if ($exeFile -match "ads-(\d+\.\d+\.\d+)-win64(?:-[a-zA-Z]+)?.exe") {
            echo "VERSION=$($matches[1])" >> $env:GITHUB_ENV
          } else {
            echo "Failed to extract version" 
            exit 1
          }

      - name: Set Tag Name
        shell: pwsh
        run: |
          if ("${{ matrix.twincat }}" -eq "ON") {
            echo "TAG_NAME=${{ env.VERSION }}-${{ matrix.build_type }}-use-twincat" >> $env:GITHUB_ENV
          } else {
            echo "TAG_NAME=${{ env.VERSION }}-${{ matrix.build_type }}-without-twincat" >> $env:GITHUB_ENV
          }

      - name: Release the Package
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ads-*-${{ matrix.build_type }}.exe
          tag: "windows_${{ env.TAG_NAME }}"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true