name: Build and Package ADS on Windows

on:
  push:
    paths:
      - .github/workflows/build-package-windows.yml
  pull_request:
    paths:
      - .github/workflows/build-package-windows.yml
permissions:
  contents: write
  pull-requests: write

jobs:
  build-package-windows:
    runs-on: [self-hosted, windows, x64, twincat]
    strategy:
      matrix:
        build_type: [Release, Debug]
    steps:
      - uses: actions/checkout@v4

      - name: Configure and Build ADS
        shell: cmd
        run: |
          set TwinCAT_ROOT=C:\TwinCAT
          echo TwinCAT_ROOT is set to %TwinCAT_ROOT%
          
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_TWINCAT_ROUTER=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build . --config ${{ matrix.build_type }}
          cpack -G NSIS64 -C ${{ matrix.build_type }}
    
          

      - name: Extract Version from Release
        shell: cmd
        run: |
          @echo off
          setlocal EnableDelayedExpansion
          cd build
          for /f "delims=" %%i in ('dir /b /o:-n ads-*.exe') do (
            set "exeFile=%%i"
            goto found
          )
          :found
          if defined exeFile (
            rem 去掉前缀 "ads-" 和后缀 ".exe" 提取版本号
            set "version=!exeFile:ads-=!"
            set "version=!version:.exe=!"
            echo VERSION=!version!>> %GITHUB_ENV%
          ) else (
            echo Failed to extract version
            exit /b 1
          )
    

      - name: Rename Executables add build_type
        shell: cmd
        run: |
          @echo off
          setlocal EnableDelayedExpansion
          cd build
          for /f "delims=" %%i in ('dir /b /o:-n ads-*.exe') do (
            set "exeFile=%%i"
            goto found
          )
          :found
          if defined exeFile (
            rem 将 .exe 替换为 -<build_type>.exe
            set "newName=!exeFile:.exe=-${{ matrix.build_type }}.exe!"
            ren "!exeFile!" "!newName!"
            echo Renamed !exeFile! to !newName!
          ) else (
            echo No executable found!
            exit /b 1
          )


      - name: Release the Package
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"
          files: |
            build/*.exe

