name: Build and Package ADS on Linux

#on:
#  push:
#    paths:
#      - .github/workflows/build-package-linux.yml
#      - deb/**
#  pull_request:
#    paths:
#      - .github/workflows/build-package-linux.yml
#      - deb/**

on: push
jobs:
  build-package-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure and Build ADS
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Package ADS with CPack
        run: |
          cd build
          cpack -G DEB

      - name:  Release the Package
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "ads-release-on_linux"
          name: "ADS Release on Linux"
          files: build/*.deb